In [1]:
data = [11,22,33,44,55,66]

In [2]:
import pandas as pd

In [3]:
price_df=pd.read_csv("prices-split-adjusted.csv")

In [4]:
price_df.head()

date symbol        open       close         low        high  \
0  2016-01-05   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

In [5]:
data

[11, 22, 33, 44, 55, 66]

In [6]:
data[2]

33

In [8]:
data[5]

66

In [9]:
data[-1]

66

In [10]:
data[1:5]

[22, 33, 44, 55]

In [11]:
data[0:5]

[11, 22, 33, 44, 55]

In [12]:
data[0:6]

[11, 22, 33, 44, 55, 66]

In [13]:
data[:4]

[11, 22, 33, 44]

In [14]:
data[2:]

[33, 44, 55, 66]

In [15]:
data[ : ]

[11, 22, 33, 44, 55, 66]

In [16]:
import numpy as np

In [17]:
type(data)

list

In [18]:
data = np.array(data)

In [19]:
type(data)

numpy.ndarray

In [22]:
data2d = [[11,22,33],[44,55,66],[77,88,99]]

In [23]:
data2d[2]

[77, 88, 99]

In [25]:
data2d[2][1]

88

In [26]:
data2d

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]

In [27]:
data2d=np.array(data2d)

In [28]:
data2d

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [29]:
data2d[2,1]

88

In [30]:
price_df.iloc[2,3]

114.949997

In [31]:
data2d

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [32]:
data2d[1:2,0:2]

array([[44, 55]])

In [34]:
data2d[1, :2]

array([44, 55])

In [35]:
data2d[ : , :2]

array([[11, 22],
       [44, 55],
       [77, 88]])

In [37]:
data2d[ : ,2]

array([33, 66, 99])

In [38]:
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   date    851264 non-null  object 
 1   symbol  851264 non-null  object 
 2   open    851264 non-null  float64
 3   close   851264 non-null  float64
 4   low     851264 non-null  float64
 5   high    851264 non-null  float64
 6   volume  851264 non-null  float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [39]:
X = price_df.iloc[ : , :6]

In [40]:
X.head()

date symbol        open       close         low        high
0  2016-01-05   WLTW  123.430000  125.839996  122.309998  126.250000
1  2016-01-06   WLTW  125.239998  119.980003  119.940002  125.540001
2  2016-01-07   WLTW  116.379997  114.949997  114.930000  119.739998
3  2016-01-08   WLTW  115.480003  116.620003  113.500000  117.440002
4  2016-01-11   WLTW  117.010002  114.970001  114.089996  117.330002

In [42]:
y=price_df.iloc[ : ,6]

In [43]:
y.head()

0    2163600.0
1    2386400.0
2    2489500.0
3    2006300.0
4    1408600.0
Name: volume, dtype: float64

In [44]:
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   date    851264 non-null  object 
 1   symbol  851264 non-null  object 
 2   open    851264 non-null  float64
 3   close   851264 non-null  float64
 4   low     851264 non-null  float64
 5   high    851264 non-null  float64
 6   volume  851264 non-null  float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [46]:
y = price_df.iloc[ : ,3]

In [47]:
X = price_df.drop(columns=["close"])

In [48]:
X.head()

date symbol        open         low        high     volume
0  2016-01-05   WLTW  123.430000  122.309998  126.250000  2163600.0
1  2016-01-06   WLTW  125.239998  119.940002  125.540001  2386400.0
2  2016-01-07   WLTW  116.379997  114.930000  119.739998  2489500.0
3  2016-01-08   WLTW  115.480003  113.500000  117.440002  2006300.0
4  2016-01-11   WLTW  117.010002  114.089996  117.330002  1408600.0

In [49]:
y.head()

0    125.839996
1    119.980003
2    114.949997
3    116.620003
4    114.970001
Name: close, dtype: float64

In [50]:
X=np.array(X)

In [51]:
y=np.array(y)

In [52]:
X.shape

(851264, 6)

In [53]:
y.shape

(851264,)

In [54]:
X.shape[0]

851264

In [55]:
X.shape[1]

6

In [56]:
X=X.reshape([X.shape[0],
            X.shape[1],
            1])

In [57]:
X.shape

(851264, 6, 1)

In [58]:
df = pd.DataFrame({"New York":[25]})

In [59]:
df

New York
0        25

In [60]:
df.melt()

variable  value
0  New York     25

In [62]:
df = pd.DataFrame({"New York":[25,26,30,28]})

In [63]:
df

New York
0        25
1        26
2        30
3        28

In [64]:
df.melt()

variable  value
0  New York     25
1  New York     26
2  New York     30
3  New York     28

In [65]:
df = pd.DataFrame({"New York":[25,26,30,28],
                  "Dublin":[10,12,14,9],
                  "Los Angeles":[30,32,36,38],
                  "Galway":[15,18,17,15]})

In [66]:
df

New York  Dublin  Los Angeles  Galway
0        25      10           30      15
1        26      12           32      18
2        30      14           36      17
3        28       9           38      15

In [67]:
df.melt()

variable  value
0      New York     25
1      New York     26
2      New York     30
3      New York     28
4        Dublin     10
5        Dublin     12
6        Dublin     14
7        Dublin      9
8   Los Angeles     30
9   Los Angeles     32
10  Los Angeles     36
11  Los Angeles     38
12       Galway     15
13       Galway     18
14       Galway     17
15       Galway     15

In [69]:
temp_df=df.melt(var_name="city",value_name="temp")

In [70]:
temp_df

city  temp
0      New York    25
1      New York    26
2      New York    30
3      New York    28
4        Dublin    10
5        Dublin    12
6        Dublin    14
7        Dublin     9
8   Los Angeles    30
9   Los Angeles    32
10  Los Angeles    36
11  Los Angeles    38
12       Galway    15
13       Galway    18
14       Galway    17
15       Galway    15

In [71]:
temperatures = pd.DataFrame({
 'city': ['New York', 'London', 'Paris', 'Berlin', 'Amsterdam'],
 'day1': [23, 25, 27, 26, 24],
 'day2': [22, 21, 25, 26, 23],
 'day3': [26, 25, 24, 27, 23],
 'day4': [23, 21, 22, 26, 27],
 'day5': [27, 26, 27, 24, 28]
})

In [72]:
temperatures

city  day1  day2  day3  day4  day5
0   New York    23    22    26    23    27
1     London    25    21    25    21    26
2      Paris    27    25    24    22    27
3     Berlin    26    26    27    26    24
4  Amsterdam    24    23    23    27    28

In [74]:
temperatures.melt(id_vars=["city"])

city variable  value
0    New York     day1     23
1      London     day1     25
2       Paris     day1     27
3      Berlin     day1     26
4   Amsterdam     day1     24
5    New York     day2     22
6      London     day2     21
7       Paris     day2     25
8      Berlin     day2     26
9   Amsterdam     day2     23
10   New York     day3     26
11     London     day3     25
12      Paris     day3     24
13     Berlin     day3     27
14  Amsterdam     day3     23
15   New York     day4     23
16     London     day4     21
17      Paris     day4     22
18     Berlin     day4     26
19  Amsterdam     day4     27
20   New York     day5     27
21     London     day5     26
22      Paris     day5     27
23     Berlin     day5     24
24  Amsterdam     day5     28

In [76]:
temp_reshape=temperatures.melt(id_vars=["city"], var_name="day",value_name="temp")

In [78]:
temp_reshape.sample(5)

city   day  temp
22      Paris  day5    27
8      Berlin  day2    26
4   Amsterdam  day1    24
18     Berlin  day4    26
2       Paris  day1    27

In [80]:
stocks = pd.read_csv('prices-split-adjusted.csv',
 usecols=['date', 'symbol', 'open', 'close'],
 parse_dates=['date'],
 index_col='date') 


In [81]:
stocks.head()

symbol        open       close
date                                     
2016-01-05   WLTW  123.430000  125.839996
2016-01-06   WLTW  125.239998  119.980003
2016-01-07   WLTW  116.379997  114.949997
2016-01-08   WLTW  115.480003  116.620003
2016-01-11   WLTW  117.010002  114.970001

In [82]:
stocks_small=stocks.loc["2016-02-01":"2016-03-01"].reset_index()

In [83]:
stocks_small.head()

date symbol        open       close
0 2016-02-01   WLTW  114.000000  114.500000
1 2016-02-02   WLTW  113.250000  110.559998
2 2016-02-03   WLTW  113.379997  114.050003
3 2016-02-04   WLTW  114.080002  115.709999
4 2016-02-05   WLTW  115.120003  114.019997

In [87]:
ssm=stocks_small.pivot(index="symbol", columns="date", values="close").reset_index()

In [88]:
ssm.head()

date symbol  2016-02-01 00:00:00  2016-02-02 00:00:00  2016-02-03 00:00:00  \
0         A            37.689999            37.070000            37.189999   
1       AAL            39.380001            37.029999            37.509998   
2       AAP           154.889999           151.860001           147.940002   
3      AAPL            96.430000            94.480003            96.349998   
4      ABBV            54.389999            53.950001            56.840000   

date  2016-02-04 00:00:00  2016-02-05 00:00:00  2016-02-08 00:00:00  \
0               37.419998            36.040001            34.799999   
1               38.209999            36.750000            35.549999   
2              147.850006           143.940002           141.449997   
3               96.599998            94.019997            95.010002   
4               56.759998            53.119999            52.889999   

date  2016-02-09 00:00:00  2016-02-10 00:00:00  2016-02-11 00:00:00  ...  \
0               35.369999            35.849998            35.330002  ...   
1               36.189999            37.119999            36.490002  ...   
2              141.500000           138.570007           138.410004  ...   
3               94.989998            94.269997            93.699997  ...   
4               53.480000            52.720001            52.180000  ...   

date  2016-02-17 00:00:00  2016-02-18 00:00:00  2016-02-19 00:00:00  \
0               37.869999            37.189999            37.439999   
1               39.340000            39.540001            39.759998   
2              143.410004           143.320007           143.630005   
3               98.120003            96.260002            96.040001   
4               55.009998            54.549999            54.290001   

date  2016-02-22 00:00:00  2016-02-23 00:00:00  2016-02-24 00:00:00  \
0               38.029999            37.169998            37.480000   
1               40.840000            40.380001            40.660000   
2              147.869995           147.550003           150.419998   
3               96.879997            94.690002            96.099998   
4               55.279999            55.070000            54.889999   

date  2016-02-25 00:00:00  2016-02-26 00:00:00  2016-02-29 00:00:00  \
0               37.630001            37.590000            37.349998   
1               41.360001            40.869999            41.000000   
2              150.080002           150.050003           148.440002   
3               96.760002            96.910004            96.690002   
4               56.200001            56.000000            54.610001   

date  2016-03-01 00:00:00  
0               38.590000  
1               41.830002  
2              153.350006  
3              100.529999  
4               56.340000  

[5 rows x 22 columns]

In [89]:
ssm.melt(id_vars=["symbol"],
        var_name="date",
        value_name="close")

symbol       date       close
0          A 2016-02-01   37.689999
1        AAL 2016-02-01   39.380001
2        AAP 2016-02-01  154.889999
3       AAPL 2016-02-01   96.430000
4       ABBV 2016-02-01   54.389999
...      ...        ...         ...
10495   YHOO 2016-03-01   32.799999
10496    YUM 2016-03-01   54.773546
10497    ZBH 2016-03-01   97.389999
10498   ZION 2016-03-01   22.309999
10499    ZTS 2016-03-01   42.099998

[10500 rows x 3 columns]