In [23]:
import numpy
from pandas import read_csv
from numpy import array
from numpy import reshape

In [2]:
data=[11,22,33,44,55]

In [4]:
data=array(data)

In [5]:
print(data)

[11 22 33 44 55]


In [6]:
print(type(data))

<class 'numpy.ndarray'>


In [7]:
data2D=[[11,22],[33,44],[55,66]]

In [8]:
data2D=array(data2D)

In [10]:
print(data2D)

[[11 22]
 [33 44]
 [55 66]]


In [11]:
print(type(data2D))

<class 'numpy.ndarray'>


In [12]:
print(data[0])
print(data[4])

11
55


In [17]:
print(data[-5])

11


In [19]:
data2D[0,1]

22

In [21]:
print(data2D[1,])

[33 44]


In [24]:
dataset=read_csv(r"C:\Users\david\Downloads\Social_Network_Ads.csv");

In [25]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [32]:
data = array([11, 22, 33, 44, 55])
print(data[0:3])

[11 22 33]


In [33]:
print(data[-2:])

[44 55]


In [38]:
X, y = data2D[:, :-1], data2D[:, -1]

In [39]:
print(X)
print(y)

[[11]
 [33]
 [55]]
[22 44 66]


In [40]:
data = array([11, 22, 33, 44, 55])

In [41]:
print(data.shape)


(5,)


In [42]:
print(data2D.shape)

(3, 2)


In [43]:
print('Rows: %d' % data2D.shape[0])
print('Cols: %d' % data2D.shape[1])

Rows: 3
Cols: 2


In [44]:
data = data.reshape((data.shape[0], 1))

In [45]:
print(data.shape)

(5, 1)
